### ISSUE TITLE
Not able to load the dumped predictions

### ISSUE THREAD

**Issue by mayank1806** [NicolasHug/Surprise#31]
Hi, I am using this library to predict ratings. I am able to dump the predictions using :
**surprise.evaluate(algo,data,with dump=True,verbose=2)** This command dumps my prediction and also prints the prediction. But I want to construct a dataframe from those predictions .I am using dump.load to load the dumped field but its throwing an **AttributeError: 'function' object has no attribute 'dump'**,
Again, Even If I try to dump my predictions using **dump.dump('./dump_file', predictions, algo)** it is throwing the same error. Can you tell me a way out for this?
I have referred this example : http://nbviewer.jupyter.org/github/NicolasHug/Surprise/blob/master/examples/notebooks/KNNBasic_analysis.ipynb . Everything can get sorted if the "dump and load " thing works.

**Comment by NicolasHug** [comment]
Hi,

What is the output of

    surprise --version

Also, are you able to run the  notebook without error?

Nicolas

**Comment by mayank1806** [comment]
scikit-surprise==1.0.2

I am running my codes in spyder. All the modules work well except dump.

**Comment by NicolasHug** [comment]
Then you'll need to update to the latest version (1.0.3).

I'm pretty sure the notebook should not work with version 1.0.2 though.

Nicolas
